fix: gPAS TTP-FHIR gateway 2.0.0 operations
miracum/fhir-pseudonymizer pull request #44
Opened 2022-04-19 17:04 UTC by jabberwoc

2022-04-21 12:53 UTC, jabberwoc commented
This PR now supports using the ttp-fhir-gateway for gPAS 1.10.3 and higher (for now).

Unit tests for those API calls here: [GPasFhirClientTests.cs](https://github.com/miracum/fhir-pseudonymizer/pull/44/files#diff-6c3eff55d744a9e6afc920138376a708dd45223263fce7da66852ac5ea71f40a)

2022-04-21 23:24 UTC, chgl requested changes
perfect, thank you! Just some internal notes/comments.

Can you check the LGTM complaint? Other than that, looks good to me!

2022-04-21 23:24 UTC, chgl commented on src/FhirPseudonymizer.Tests/GPasFhirClientTests.cs
> +        "{\"resourceType\":\"Parameters\",\"parameter\":[{\"name\":\"pseudonym\",\"part\":[{\"name\":\"original\",\"valueIdentifier\":{\"system\":\"https://ths-greifswald.de/gpas\",\"value\":\"1\"}},
Just a mental note to switch to C#11's raw string literals once available for better readability.

2022-04-21 23:24 UTC, chgl commented on src/FhirPseudonymizer.Tests/GPasFhirClientTests.cs
> +using Moq;
The previous tests used https://fakeiteasy.github.io/ instead of Moq, since its just a test-dependency I personally don't mind too much. But maybe a note to eventually settle on one or the other for consistency.

2022-04-21 23:24 UTC, chgl commented on src/FhirPseudonymizer/GPasFhirClient.cs
> +                GetOrCreatePseudonymForResolver = GetOrCreatePseudonymForV1;
that's a much nicer and cleaner solution! thanks for refactoring!

2022-04-22 22:41 UTC, jabberwoc commented on src/FhirPseudonymizer.Tests/GPasFhirClientTests.cs
> +using Moq;
Refactored the tests to use FakeItEasy instead of Moq. Nice Mocking Framework and more readable and concise. :)

2022-04-22 22:44 UTC, jabberwoc commented
Thanks for the review, @chgl 

I will merge this later if there's nothing to more to request.

2022-04-23 16:26 UTC, chgl approved these changes

2022-04-23 16:26 UTC, merged